Error de indexacion en config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,7 +9,9 @@ jobs:
   steps:
    - checkout
    - setup_remote_docker
+  
 
+  
     - run:
       name: Build application container
       command: | 
@@ -19,22 +21,22 @@ jobs:
         cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
         docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
 
-  - run:
-    name: Run application in Background
-    command: |
+    - run:
+      name: Run application in Background
+      command: |
       docker run ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
       background: true
 
-  - run:
-    name: ZAP baseline scan of application
-    # Only fail on error code 1, which indicates at least one FAIL was found.
-    # error codes 2 & 3 indicate WARN or other, and should not break the run
-    command: |
-      (
-      docker pull owasp/zap2docker-weekly && \
-      docker run -t owasp/zap2docker-weekly zap-baseline.py \
-      -u 
-      https://raw.githubusercontent.com/${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
-        -t http://172.17.0.2:8080/ || \
-      if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-    )
+    - run:
+      name: ZAP baseline scan of application
+      # Only fail on error code 1, which indicates at least one FAIL was found.
+      # error codes 2 & 3 indicate WARN or other, and should not break the run
+      command: |
+        (
+        docker pull owasp/zap2docker-weekly && \
+        docker run -t owasp/zap2docker-weekly zap-baseline.py \
+        -u 
+        https://raw.githubusercontent.com/${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
+          -t http://172.17.0.2:8080/ || \
+        if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+        )
